version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: finsight
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: finsight_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api_gateway:
    image: nginx:alpine
    volumes:
      - ./services/api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - auth_service
      - transaction_service
      - budget_service
      - analytics_service

  auth_service:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "services.auth_service.main:app", "--host", "0.0.0.0", "--port", "8001"]
    environment:
      - DATABASE_URL=postgresql://finsight:secretpassword@db/finsight_db
    env_file:
      - .env
    depends_on:
      - db

  transaction_service:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "services.transaction_service.main:app", "--host", "0.0.0.0", "--port", "8002"]
    environment:
      - DATABASE_URL=postgresql://finsight:secretpassword@db/finsight_db
      - REDIS_URL=redis://redis:6379/
    env_file:
      - .env
    depends_on:
      - db
      - redis

  budget_service:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "services.budget_service.main:app", "--host", "0.0.0.0", "--port", "8003"]
    environment:
      - DATABASE_URL=postgresql://finsight:secretpassword@db/finsight_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  budget_worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "services.budget_service.budget.tasks", "worker", "--loglevel=info"]
    environment:
      - DATABASE_URL=postgresql://finsight:secretpassword@db/finsight_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db

  analytics_service:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "services.analytics_service.main:app", "--host", "0.0.0.0", "--port", "8004"]
    environment:
      - DATABASE_URL=postgresql://finsight:secretpassword@db/finsight_db
      - REDIS_URL=redis://redis:6379/
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
