"""Initial schema

Revision ID: 23f41d8a0ac5
Revises: 
Create Date: 2026-04-16 19:34:17.034605

"""
from typing import Sequence, Union

from services.shared.alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f41d8a0ac5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency_pairs', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rate_cache_currency_pairs'), 'exchange_rate_cache', ['currency_pairs'], unique=True)
    op.create_index(op.f('ix_exchange_rate_cache_id'), 'exchange_rate_cache', ['id'], unique=False)
    op.create_table('investment_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_cache_id'), 'investment_cache', ['id'], unique=False)
    op.create_index(op.f('ix_investment_cache_symbol'), 'investment_cache', ['symbol'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant'), 'transactions', ['merchant'], unique=False)
    op.create_index(op.f('ix_transactions_source'), 'transactions', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_source'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_investment_cache_symbol'), table_name='investment_cache')
    op.drop_index(op.f('ix_investment_cache_id'), table_name='investment_cache')
    op.drop_table('investment_cache')
    op.drop_index(op.f('ix_exchange_rate_cache_id'), table_name='exchange_rate_cache')
    op.drop_index(op.f('ix_exchange_rate_cache_currency_pairs'), table_name='exchange_rate_cache')
    op.drop_table('exchange_rate_cache')
    # ### end Alembic commands ###
