events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth_service:8001;
    }
    upstream transaction_service {
        server transaction_service:8002;
    }
    upstream budget_service {
        server budget_service:8003;
    }
    upstream analytics_service {
        server analytics_service:8004;
    }

    server {
        listen 80;

        location /auth {
            proxy_pass http://auth_service/auth;
        }

        location /ingestion {
            proxy_pass http://transaction_service/ingestion;
        }
        
        location /categorization {
            proxy_pass http://transaction_service/categorization;
        }

        location /currency {
            proxy_pass http://transaction_service/currency;
        }

        location /budget {
            proxy_pass http://budget_service/budget;
        }

        location /recommendations {
            proxy_pass http://analytics_service/recommendations;
        }

        location /reports {
            proxy_pass http://analytics_service/reports;
        }
        
        location /investments {
            proxy_pass http://analytics_service/investments;
        }
    }
}
